import { Metadata } from "next"

import Hero from "@modules/home/components/hero"

export const metadata: Metadata = {
  title: "BEEMUN — ZPS 100 Marketplace",
  description: "A curated marketplace for products reviewed for zero plastic, zero synthetic, full disclosure, and maker accountability.",
}

const trust = [["♻","Zero Plastic","No product goes live without packaging disclosure and review."],["✦","Zero Synthetic","We look beyond vague natural claims and check ingredient clarity."],["✓","Full Disclosure","Ingredients, packaging, maker details, and claims stay visible before purchase."],["◎","BEEMUN Reviewed","Every listing is screened before customers see it."]]
const categories = [["◐","Skin & Body","Body oils, balms, butters, and personal care essentials."],["≋","Hair Care","Hair oils, powders, cleansers, and scalp-care routines."],["●","Oils & Butters","Single-ingredient oils and simple, honest formulations."],["⌂","Home Products","Everyday home essentials with packaging visibility."]]
const products = [["◉","Cold Pressed Coconut Oil","Earth Roots","Single ingredient oil · glass bottle","₹349"],["✿","Rose Face Balm","Petal & Soil","Botanical balm · recyclable jar","₹599"],["◌","Hibiscus Hair Powder","Root Rituals","Full ingredient disclosure","₹249"]]
const reviewSteps = [["01","Seller applies","Makers share brand details, product philosophy, and basic documents."],["02","Product is submitted","Ingredients, packaging, claims, images, and sourcing notes are shared."],["03","BEEMUN reviews","Ingredient clarity, packaging clarity, and claim language are checked."],["04","Product goes live","Approved products become visible with ZPS trust signals."]]
const zps = [["♻","Zero Plastic","Packaging and shipping materials are reviewed for plastic-free intent."],["✦","Zero Synthetic","No artificial fragrance, colours, preservatives, or hidden synthetic additives."],["✓","Full Disclosure","Ingredients and packaging components must be clearly declared."],["◎","BEEMUN Reviewed","Products are screened before customers see them."]]
const makers = [["E","Earth Roots","Single-ingredient oils and simple natural care from accountable sourcing."],["P","Petal & Soil","Small-batch balms, butters, and botanical blends with clear labels."],["R","Root Rituals","Herbal powders and care essentials built around visible ingredients."]]
const collections = [["Founder Favorites","Trusted products personally selected for early BEEMUN customers."],["New Arrivals","Recently approved products added to the ZPS marketplace."],["Seasonal Picks","Useful essentials for weather, routines, and gifting moments."],["Gift Collection","Simple, thoughtful products with clearer labels and packaging notes."]]
const promises = [["No ingredient guessing","Customers see what is inside before they buy."],["No vague packaging claims","Packaging notes stay part of the product experience."],["No hidden synthetic surprises","Labels and claims are reviewed for clarity."],["Maker accountability","The maker behind the product stays visible."]]
const faqs = [["Is BEEMUN a normal ecommerce store?","No. BEEMUN is a curated marketplace where products are reviewed for disclosure and ZPS trust signals before they go live."],["What does ZPS 100 mean?","It represents BEEMUN’s zero plastic, zero synthetic, full disclosure, and review-led product direction."],["Can small makers sell on BEEMUN?","Yes. BEEMUN is designed for serious small brands that can stand behind their ingredients, packaging, and product claims."],["Will products show full ingredients?","Yes. Ingredient and packaging clarity are core to the BEEMUN shopping experience."]]

export default async function Home() {
  return (
    <>
      <Hero />
      <section className="beemun-section"><div className="beemun-four-grid">{trust.map(([icon,title,text])=><article className="beemun-card beemun-trust-card" key={title}><div className="beemun-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="beemun-section beemun-story-section"><div><p className="beemun-eyebrow">Why BEEMUN exists</p><h2>Clean should not be a guessing game.</h2></div><p>Most products look pure on the outside, but customers still have to guess what is inside, how it is packed, and whether the maker’s claims are real. BEEMUN is built to reduce that guesswork by making disclosure, review, and maker accountability part of the shopping experience.</p></section>
      <section className="beemun-section"><div className="beemun-section-head"><p className="beemun-eyebrow">What makes BEEMUN different</p><h2>Not just natural. Reviewed for purity.</h2><p>Most marketplaces only show seller claims. BEEMUN shows customers what the product contains, how it is packed, and why it is allowed to go live.</p></div><div className="beemun-three-grid"><article className="beemun-card"><div className="beemun-icon">✓</div><h3>Ingredient Transparency</h3><p>Full ingredient disclosure is required before listing so customers do not have to decode unclear claims.</p></article><article className="beemun-card"><div className="beemun-icon">▣</div><h3>Packaging Transparency</h3><p>Primary, label, and shipping packaging are reviewed so customers know what arrives with the product.</p></article><article className="beemun-card"><div className="beemun-icon">100</div><h3>ZPS 100 Standard</h3><p>Products are screened for zero plastic intent, zero synthetic intent, full disclosure, and review readiness.</p></article></div></section>
      <section className="beemun-section beemun-soft-section" id="categories"><div className="beemun-section-head"><p className="beemun-eyebrow">Shop by category</p><h2>Start with curated ZPS 100 categories.</h2><p>Explore daily essentials through a trust-first lens.</p></div><div className="beemun-four-grid">{categories.map(([icon,title,text])=><article className="beemun-card beemun-category-card" key={title}><div className="beemun-visual-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="beemun-section" id="featured"><div className="beemun-section-head"><p className="beemun-eyebrow">Featured products</p><h2>ZPS 100 products, curated first.</h2><p>These preview cards show the kind of product experience BEEMUN will offer: clear ingredients, packaging notes, maker visibility, and trust-first buying.</p></div><div className="beemun-three-grid">{products.map(([icon,title,maker,note,price])=><article className="beemun-product-card" key={title}><div className="beemun-product-visual"><span>{icon}</span></div><span>ZPS 100</span><h3>{title}</h3><p>by {maker}</p><small>{note}</small><strong>{price}</strong></article>)}</div></section>
      <section className="beemun-section beemun-soft-section"><div className="beemun-section-head"><p className="beemun-eyebrow">How BEEMUN works</p><h2>Every product goes through a trust-first review.</h2></div><div className="beemun-four-grid">{reviewSteps.map(([num,title,text])=><article className="beemun-card" key={title}><span className="beemun-step">{num}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="beemun-section" id="zps"><div className="beemun-zps-grid"><div><p className="beemun-eyebrow">ZPS 100 standard</p><h2>What ZPS 100 means.</h2><p>ZPS 100 is BEEMUN’s trust direction for products that are zero plastic, zero synthetic, fully disclosed, and reviewed before going live.</p></div><div className="beemun-four-mini-grid">{zps.map(([icon,title,text])=><article className="beemun-card" key={title}><div className="beemun-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="beemun-section beemun-promise"><div className="beemun-section-head"><p className="beemun-eyebrow">Customer promise</p><h2>Know more before you buy.</h2><p>BEEMUN is designed to make transparency visible before checkout, not after disappointment.</p></div><div className="beemun-four-grid">{promises.map(([title,text])=><article className="beemun-card" key={title}><div className="beemun-icon">✓</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="beemun-section"><div className="beemun-section-head"><p className="beemun-eyebrow">Ingredient discovery</p><h2>Explore by ingredient.</h2><p>Discover products through ingredients they are built around.</p></div><div className="beemun-pill-row">{["Neem","Rose","Coconut","Hibiscus","Beeswax","Amla"].map(i=><span key={i}>{i}</span>)}</div></section>
      <section className="beemun-section beemun-soft-section"><div className="beemun-section-head"><p className="beemun-eyebrow">Meet the makers</p><h2>Small brands. Serious transparency.</h2><p>BEEMUN highlights makers who stand behind their ingredients, packaging, and product claims.</p></div><div className="beemun-three-grid">{makers.map(([mark,title,text])=><article className="beemun-maker-card" key={title}><div className="beemun-maker-mark">{mark}</div><h3>{title}</h3><p>{text}</p><a href="#">View brand</a></article>)}</div></section>
      <section className="beemun-section"><div className="beemun-section-head"><p className="beemun-eyebrow">Collections</p><h2>Curated collections.</h2><p>Collections help customers shop with purpose instead of scrolling endlessly.</p></div><div className="beemun-four-grid">{collections.map(([title,text])=><article className="beemun-card beemun-category-card" key={title}><div className="beemun-card-image"/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="beemun-section beemun-faq"><div className="beemun-section-head"><p className="beemun-eyebrow">Questions</p><h2>Before you shop.</h2></div><div className="beemun-faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
      <section className="beemun-newsletter"><p className="beemun-eyebrow">Early access</p><h2>Be first to discover ZPS 100 products.</h2><p>Join the BEEMUN list for launch updates, maker stories, and curated product drops.</p><div><input placeholder="Enter your email"/><button>Join Early Access</button></div></section>
      <section className="beemun-seller-cta" id="partner"><p className="beemun-eyebrow">For makers</p><h2>Are you a purity-first maker?</h2><p>Join BEEMUN and bring genuinely transparent, zero-plastic, zero-synthetic products to customers who care about what they buy.</p><a className="beemun-btn-primary" href="#">Partner with BEEMUN</a></section>
    </>
  )
}
