import { Metadata } from "next"

import Hero from "@modules/home/components/hero"

export const metadata: Metadata = {
  title: "BEEMUN — ZPS 100 Marketplace",
  description: "A curated marketplace for products reviewed for zero plastic, zero synthetic, full disclosure, and maker accountability.",
}

const trust = [["Zero Plastic","Packaging reviewed before products go live."],["Zero Synthetic","Ingredient labels checked for hidden synthetic claims."],["Full Disclosure","Ingredients, packaging, and maker details stay visible."],["BEEMUN Reviewed","Products pass a trust-first listing review."]]
const categories = [["Skin & Body","Clean daily care with ingredient transparency."],["Hair Care","Oils, cleansers, and routines with clearer labels."],["Oils & Butters","Single-ingredient oils and simple formulations."],["Home Care","Useful home products with packaging visibility."]]
const products = [["Cold Pressed Coconut Oil","Earth Roots","Single-ingredient oil","₹349"],["Rose Face Balm","Petal & Soil","Glass jar packaging","₹599"],["Hibiscus Hair Powder","Root Rituals","Full ingredient disclosure","₹249"]]
const reviewSteps = [["01","Seller applies","Makers submit brand and product details."],["02","Product is submitted","Ingredients, packaging, claims, images, and notes are shared."],["03","BEEMUN reviews","Ingredient, packaging, and disclosure standards are checked."],["04","Product goes live","Only approved ZPS-ready products become visible."]]
const zps = [["Zero Plastic","Packaging and shipping materials are reviewed for plastic-free intent."],["Zero Synthetic","No artificial fragrance, colours, preservatives, or hidden synthetic additives."],["Full Disclosure","Ingredients and packaging components must be clearly declared."],["BEEMUN Reviewed","Products are screened before customers see them."]]
const makers = [["Earth Roots","Single-ingredient oils and simple natural care."],["Petal & Soil","Small-batch balms, butters, and botanical blends."],["Root Rituals","Herbal powders and personal care essentials."]]
const collections = [["Founder Favorites","Trusted products personally selected for early customers."],["New Arrivals","Recently approved products added to BEEMUN."],["Seasonal Picks","Useful products for current routines and weather."],["Gift Collection","Simple, thoughtful products with clearer labels."]]

export default async function Home() {
  return (
    <>
      <Hero />
      <section className="beemun-section"><div className="beemun-four-grid">{trust.map(([title,text])=><article className="beemun-card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="beemun-section"><div className="beemun-section-head"><p className="beemun-eyebrow">What makes BEEMUN different</p><h2>Not just natural. Reviewed for purity.</h2><p>Most marketplaces only show seller claims. BEEMUN shows customers what the product contains, how it is packed, and why it is allowed to go live.</p></div><div className="beemun-three-grid"><article className="beemun-card"><h3>Ingredient Transparency</h3><p>Full ingredient disclosure is required before listing.</p></article><article className="beemun-card"><h3>Packaging Transparency</h3><p>Primary, label, and shipping packaging are reviewed.</p></article><article className="beemun-card"><h3>ZPS 100 Standard</h3><p>Products are screened for zero plastic and zero synthetic intent.</p></article></div></section>
      <section className="beemun-section beemun-soft-section" id="categories"><div className="beemun-section-head"><p className="beemun-eyebrow">Shop by category</p><h2>Start with curated ZPS 100 categories.</h2><p>Explore daily essentials through a trust-first lens.</p></div><div className="beemun-four-grid">{categories.map(([title,text])=><article className="beemun-card beemun-category-card" key={title}><div className="beemun-card-image"/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="beemun-section" id="featured"><div className="beemun-section-head"><p className="beemun-eyebrow">Featured products</p><h2>ZPS 100 products, curated first.</h2><p>Preview the type of product cards customers will see once BEEMUN products are added to the catalog.</p></div><div className="beemun-three-grid">{products.map(([title,maker,note,price])=><article className="beemun-product-card" key={title}><div className="beemun-card-image"/><span>ZPS 100</span><h3>{title}</h3><p>by {maker}</p><small>{note}</small><strong>{price}</strong></article>)}</div></section>
      <section className="beemun-section beemun-soft-section"><div className="beemun-section-head"><p className="beemun-eyebrow">How BEEMUN works</p><h2>Every product goes through a trust-first review.</h2></div><div className="beemun-four-grid">{reviewSteps.map(([num,title,text])=><article className="beemun-card" key={title}><span className="beemun-step">{num}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="beemun-section" id="zps"><div className="beemun-zps-grid"><div><p className="beemun-eyebrow">ZPS 100 standard</p><h2>What ZPS 100 means.</h2><p>ZPS 100 is BEEMUN’s review direction for products that are zero plastic, zero synthetic, fully disclosed, and reviewed before going live.</p></div><div className="beemun-four-mini-grid">{zps.map(([title,text])=><article className="beemun-card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="beemun-section"><div className="beemun-section-head"><p className="beemun-eyebrow">Ingredient discovery</p><h2>Explore by ingredient.</h2><p>Discover products through ingredients they are built around.</p></div><div className="beemun-pill-row">{["Neem","Rose","Coconut","Hibiscus","Beeswax","Amla"].map(i=><span key={i}>{i}</span>)}</div></section>
      <section className="beemun-section beemun-soft-section"><div className="beemun-section-head"><p className="beemun-eyebrow">Meet the makers</p><h2>Small brands. Serious transparency.</h2><p>BEEMUN highlights makers who stand behind their ingredients, packaging, and product claims.</p></div><div className="beemun-three-grid">{makers.map(([title,text])=><article className="beemun-maker-card" key={title}><div className="beemun-maker-mark">{title[0]}</div><h3>{title}</h3><p>{text}</p><a href="#">View brand</a></article>)}</div></section>
      <section className="beemun-section"><div className="beemun-section-head"><p className="beemun-eyebrow">Collections</p><h2>Curated collections.</h2></div><div className="beemun-four-grid">{collections.map(([title,text])=><article className="beemun-card beemun-category-card" key={title}><div className="beemun-card-image"/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="beemun-seller-cta" id="partner"><p className="beemun-eyebrow">For makers</p><h2>Are you a purity-first maker?</h2><p>Join BEEMUN and bring genuinely transparent, zero-plastic, zero-synthetic products to customers who care about what they buy.</p><a className="beemun-btn-primary" href="#">Partner with BEEMUN</a></section>
    </>
  )
}
